# This file was generated by GoReleaser. DO NOT EDIT.
cask "bomly" do
  version "0.14.15"

  on_macos do
    on_intel do
      sha256 "c36ecfe3854d22e8c771640d51e10157751874874d9e38e70f58510ea531d36b"
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v#{version}/bomly_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6f1c85f7665c7e236ae4afbe43fc3435886548715a13e274adbc7a4cd2c97f7"
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v#{version}/bomly_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1ed540053ed8de7997cb8176b808c905ed8b69af521131167c575a0ceb91d6c0"
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v#{version}/bomly_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d3f8132e63d53205f05374e3cd0b6ee93ab0edc9c1b23efb1d68a0fa72cc4b8"
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v#{version}/bomly_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bomly"
  desc "Free, open-source CLI for dependency intelligence and SBOM analysis."
  homepage "https://bomly.dev/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bomly"

  # No zap stanza required

  caveats <<~EOS
    Bomly is installed as the `bomly` command.
  EOS
end
