# This file was generated by GoReleaser. DO NOT EDIT.
cask "bomly" do
  version "0.14.13"

  on_macos do
    on_intel do
      sha256 "cbbe704057742bcaaca291d2c5cc2a91fcabc4e4a211bc2dc910904c91acdc3c"
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v#{version}/bomly_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e95480f2d39cfeecbc62fcf7fae8781beb271a95143c1132322a0b4ae3fcbd9"
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v#{version}/bomly_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "920c0523cd0bc391b67abc00ec56a999b42f9e07432b43d703bf200489a93bd6"
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v#{version}/bomly_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d5282bf12f98278f55eae02e46913818c193b3316c2c52b067d9438a35d0a9ca"
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v#{version}/bomly_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bomly"
  desc "Free, open-source CLI for dependency intelligence and SBOM analysis."
  homepage "https://bomly.dev/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bomly"

  # No zap stanza required

  caveats <<~EOS
    Bomly is installed as the `bomly` command.
  EOS
end
