# This file was generated by GoReleaser. DO NOT EDIT.
cask "bomly" do
  version "0.15.0"

  on_macos do
    on_intel do
      sha256 "a93be8aa51cecfb619d154e5be8fd135def4487a090fb4701f0ee41d3c4a4631"
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v#{version}/bomly_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8dff4db42109f9f2cb2cf1967136fde44c0c0515a3e964d1cb67d173a30fc4c2"
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v#{version}/bomly_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "608141f00ebd984f65cab1374d453fcc78c7f8ff8e9f6a8f55309157ff3e52c6"
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v#{version}/bomly_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e88f8eb2bc4fa341bbb081db1db4aca3a059496b5d216f41a27938889a2c73d4"
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v#{version}/bomly_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bomly"
  desc "Free, open-source CLI for dependency intelligence and SBOM analysis."
  homepage "https://bomly.dev/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bomly"

  # No zap stanza required

  caveats <<~EOS
    Bomly is installed as the `bomly` command.
  EOS
end
