# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bomly < Formula
  desc "Free, open-source CLI for dependency intelligence and SBOM analysis"
  homepage "https://bomly.dev/cli"
  version "0.28.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v0.28.2/bomly_0.28.2_darwin_amd64.tar.gz"
      sha256 "9d2c77f0d0751aca5777622bbbd623c5b182463933d9e4a5f8f1a49dcea15b87"

      define_method(:install) do
        bin.install "bomly"
        doc.install "LICENSE", "NOTICE"
        doc.install "licenses"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v0.28.2/bomly_0.28.2_darwin_arm64.tar.gz"
      sha256 "dd91873110c76313eccc3879f32b9725b9511a78d3be802dc357a568098c1897"

      define_method(:install) do
        bin.install "bomly"
        doc.install "LICENSE", "NOTICE"
        doc.install "licenses"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v0.28.2/bomly_0.28.2_linux_amd64.tar.gz"
      sha256 "46ab415c558fb2e9ecc2f7528f18b391920805cfff5e0f126034e6ad6a65453c"
      define_method(:install) do
        bin.install "bomly"
        doc.install "LICENSE", "NOTICE"
        doc.install "licenses"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v0.28.2/bomly_0.28.2_linux_arm64.tar.gz"
      sha256 "fc62eb515a1a3417737447af2f8f8a7cbd09b1f5d49ece558bec36cd67baabe9"
      define_method(:install) do
        bin.install "bomly"
        doc.install "LICENSE", "NOTICE"
        doc.install "licenses"
      end
    end
  end

  test do
    system "#{bin}/bomly", "version"
  end
end
