# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bomly < Formula
  desc "Free, open-source CLI for dependency intelligence and SBOM analysis"
  homepage "https://bomly.dev/cli"
  version "0.23.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v0.23.0/bomly_0.23.0_darwin_amd64.tar.gz"
      sha256 "b2a41ec1a7760daa6669905e2bfbbf34b0e3dae848be797d890fe9e9cc815267"

      define_method(:install) do
        bin.install "bomly"
        doc.install "LICENSE", "NOTICE"
        doc.install "licenses"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v0.23.0/bomly_0.23.0_darwin_arm64.tar.gz"
      sha256 "3afdde21cb464746e0790cb3de36dbd1e3e8ebb673980459cd9cfb13c8b68dbd"

      define_method(:install) do
        bin.install "bomly"
        doc.install "LICENSE", "NOTICE"
        doc.install "licenses"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v0.23.0/bomly_0.23.0_linux_amd64.tar.gz"
      sha256 "87d320338a070b2b5c9123f1ee1a7eeb72f4521b2c6a6ad81d90f2d9b99c5ff7"
      define_method(:install) do
        bin.install "bomly"
        doc.install "LICENSE", "NOTICE"
        doc.install "licenses"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bomly-dev/bomly-cli/releases/download/v0.23.0/bomly_0.23.0_linux_arm64.tar.gz"
      sha256 "98cc7750a1f74e904ada17e06038734910448854cdf68793adfd784d45675276"
      define_method(:install) do
        bin.install "bomly"
        doc.install "LICENSE", "NOTICE"
        doc.install "licenses"
      end
    end
  end

  test do
    system "#{bin}/bomly", "version"
  end
end
